version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mycloudx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mycloudx
      MYSQL_USER: mycloudx
      MYSQL_PASSWORD: mycloudxpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mycloudx-network

volumes:
  mysql_data:

networks:
  mycloudx-network:
    driver: bridge 